# Generated by Django 5.2.17 on 2026-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="faculty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("health", "Health Sciences"),
                    ("engineering", "Engineering & Built Environment"),
                    ("applied", "Applied Sciences"),
                    ("arts", "Arts & Design"),
                    ("accounting", "Accounting & Informatics"),
                    ("management", "Management Sciences"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_of_study",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st year"),
                    ("2", "2nd year"),
                    ("3", "3rd year"),
                    ("4", "4th year"),
                    ("pg", "Postgraduate"),
                ],
                max_length=2,
            ),
        ),
    ]
