# Generated by Django 5.2.17 on 2026-09-22 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("math", "Numeracy"),
                            ("reading", "Reading fluency"),
                            ("writing", "Writing & language"),
                            ("memory", "Working memory"),
                            ("scenario", "Executive function"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("flagged", models.BooleanField(default=False)),
                ("detail", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_results",
                        to="screening.screeningsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "domain")},
            },
        ),
    ]
